#!/bin/tcsh


switch ($1)

	case heidelberg
	#rsync -av cass barty@lfs3.mpi-hd.mpg.de:oldcass/mimicass
	breaksw
	
	case mms1:
	#rsync -av cass barty@mms1.desy.de:local/cass/mimicass
	breaksw
	
	case cfelsgi:
	rsync -av --exclude 'build' --exclude '.git' . barty@cfelsgi.desy.de:local/c/cheetah/
	breaksw
	
	case psexport:
	#rsync -av --delete-after --exclude '.git' . barty@psexport.slac.stanford.edu:cspad
	#rsync -av --delete-after --exclude '*.o' --exclude 'release' --exclude '.git' . barty@psexport.slac.stanford.edu:cspad
	rsync -av --exclude 'release' --exclude 'build' --exclude '.git' --exclude '*.o' . barty@psexport.slac.stanford.edu:c/cheetah/
	breaksw
	
	case feldkamp:
	rsync -av --exclude 'release' --exclude 'cheetah.xcodeproj' --exclude 'xcca/xcca_commandline.xcodeproj' --exclude '.git' --exclude '*.o' --exclude 'xcca/*.o' --exclude 'xcca/matlib_support_files/*.o' . feldkamp@psexport.slac.stanford.edu:cheetah/
	breaksw
	
	case sellberg:
	rsync -r -a -v -e "ssh -l sellberg" --delete --exclude 'release' --exclude '.git' --exclude '*.o' --exclude 'cheetah' --exclude 'cheetah.xcodeproj' . psexport.slac.stanford.edu:/reg/neh/home/sellberg/source/cheetah/
	breaksw

	case xcca:
	rsync -r -a -v -e "ssh -l sellberg" --delete --exclude 'release' --exclude '.git' --exclude '*.o' --exclude 'cheetah' --exclude 'cheetah.xcodeproj' . psexport.slac.stanford.edu:/reg/d/psdm/cxi/cxi35711/scratch/cheetah/
	breaksw

	case llcp:
	rsync -r -a -v -e "ssh -l sellberg" --delete --exclude 'release' --exclude '.git' --exclude '*.o' --exclude 'cheetah' --exclude 'cheetah.xcodeproj' . psexport.slac.stanford.edu:/reg/d/psdm/cxi/cxi25410/scratch/cheetah/
	breaksw
	
	case duaneloh:
	rsync -rav --exclude '.git' --exclude '*.o' --exclude 'cheetah' --exclude 'cheetah.xcworkspace' . -e ssh duaneloh@psexport.slac.stanford.edu:working_dir/cheetah_hitfinder/cheetah/
	
endsw
